[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/forge'
cache_path  = 'cache_forge'
remappings = [
    '@chainlink/=node_modules/@chainlink/',
    '@ensdomains/=node_modules/@ensdomains/',
    '@gelatonetwork/=node_modules/@gelatonetwork/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@uniswap/=node_modules/@uniswap/',
    '@axelar-network/=node_modules/@axelar-network/',
    'base64-sol/=node_modules/base64-sol/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'forge-std/=node_modules/forge-std/',
    'lib/forge-std:ds-test/=lib/forge-std/lib/ds-test/src/',
]